server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: cambio_service
    user: test
    password: test
springdoc:
  api-docs:
    path: /cambio-service/v3/api-docs