version: '3.4'

services:
  naming-server:
    image: andoliver46/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - book-network
  api-gateway:
    image: andoliver46/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    networks:
      - book-network
    depends_on:
      - naming-server
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      
  cambio-service:
    image: andoliver46/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    ports:
      - 8000:8000
    networks:
      - book-network
    depends_on:
      - naming-server
      - cambio-db
    environment:
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3306/cambio_service?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: test
      SPRING.DATASOURCE.PASSWORD: test
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3306/cambio_service?useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.USER: test
      SPRING.FLYWAY.PASSWORD: test
      
  cambio-db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    networks:
      - book-network
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
  book-db:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    networks:
      - book-network
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - book-network
networks:
  book-network:
    driver: bridge
    